// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVYNjOoartOrRGeG0b0MYR0cKM_wFnnTc',
    appId: '1:1066422850226:web:19b8b697280a0dc0712fab',
    messagingSenderId: '1066422850226',
    projectId: 'cards-a632b',
    authDomain: 'cards-a632b.firebaseapp.com',
    storageBucket: 'cards-a632b.appspot.com',
    measurementId: 'G-NGVN6QKEJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZo4N_NUlJNsBzNKS_tkfPmNtwcCjK6fo',
    appId: '1:1066422850226:android:6ebd029850704ca2712fab',
    messagingSenderId: '1066422850226',
    projectId: 'cards-a632b',
    storageBucket: 'cards-a632b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNv-CJOlsSIeO54cqlZtg2chbVT6Kf-bM',
    appId: '1:1066422850226:ios:f8cb729c8d274456712fab',
    messagingSenderId: '1066422850226',
    projectId: 'cards-a632b',
    storageBucket: 'cards-a632b.appspot.com',
    iosBundleId: 'com.example.cards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNv-CJOlsSIeO54cqlZtg2chbVT6Kf-bM',
    appId: '1:1066422850226:ios:61c6baa55fab596f712fab',
    messagingSenderId: '1066422850226',
    projectId: 'cards-a632b',
    storageBucket: 'cards-a632b.appspot.com',
    iosBundleId: 'com.example.cards.RunnerTests',
  );
}
